> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  
function2 = np.shape
function3 = np.eye
function4 = np.ones
function5 = np.linspace

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [5]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [6]:
# Example 2 - working
arr1=[[5,6],
     [1,2]]


Explanation about example

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [8]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [12]:
# Example 1 - working
ar=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])

Explanation about example

In [13]:
# Example 2 - working
ar.shape

(3, 3)

Explanation about example

In [38]:
ar=([1,2,3],
   [4,5,6])
ar.shape

AttributeError: 'tuple' object has no attribute 'shape'

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [16]:
# Example 1 - working
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Explanation about example

In [17]:
# Example 2 - working
np.eye(1)

array([[1.]])

Explanation about example

In [37]:
# Example 3 - breaking (to illustrate when it breaks)
np.eye(,3)

SyntaxError: invalid syntax (1025870474.py, line 2)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [24]:
# Example 1 - working
np.ones(4)

array([1., 1., 1., 1.])

Explanation about example

In [26]:
# Example 2 - working
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
np.ones([0])

array([], dtype=float64)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [30]:
# Example 1 - working
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

Explanation about example

In [31]:
# Example 2 - working
np.linspace(3,10,2)

array([ 3., 10.])

Explanation about example

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
np.arrange(4)

AttributeError: module 'numpy' has no attribute 'arrange'

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115054/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115054/numpy-array-operations


'https://jovian.com/2115054/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>